# Generated by Django 5.2.4 on 2025-07-15 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polizas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poliza',
            name='asegurado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.asegurado'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='aseguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.aseguradora'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='contratante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.contratante'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poliza',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.formapago'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.ramo'),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
