# Generated by Django 3.2.20 on 2025-08-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='prima_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
