# Generated by Django 3.2.20 on 2025-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_poliza_prima_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='monto_asegurado',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
