# Generated by Django 3.2.20 on 2025-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_poliza_monto_asegurado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contratante',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
